### ISSUE TITLE
Care and Feeding of Data Scientists

### ISSUE THREAD

**Issue by mdagost** [ronikobrosly/awesome-data-leadership#3]
Not sure the best place to put this, but @cmmalone and I wrote a report for O'Reilly on DS management called "The Care and Feeding of Data Science".  A pdf is available [here](https://oreilly-ds-report.s3.amazonaws.com/Care_and_Feeding_of_Data_Scientists.pdf).

**Comment by ronikobrosly** [comment]
@mdagost and @cmmalone, this book is solid, 24K gold. Thank you so much for putting this out into the world. I just skimmed through the chapter and subsection titles and need to really devote time to reading fully in the coming weeks.

As for this repo, it seems like it could fit into multiple categories! At a quick glance the chapters could be separate entries in different repo categories. Would you mind opening a PR to add them to the categories you think are best fitting? 

For example, "CHAPTER 5: To Agile or Not to Agile" could fit into the ["Project Management"](https://github.com/ronikobrosly/awesome-data-leadership#project-management) category in this repo. 

"CHAPTER 3: Interview with the Data Scientist" could fit into the ["Hiring"](https://github.com/ronikobrosly/awesome-data-leadership#project-management) category I imagine.

Etc etc

**Comment by mdagost** [comment]
Great!  See #4!
