### ISSUE TITLE
[The Modern Data Stack Ecosystem: Spring 2022 Edition] link returns 404

### ISSUE THREAD

**Issue by farmanp** [ronikobrosly/awesome-data-leadership#6]
[The Modern Data Stack Ecosystem: Spring 2022 Edition](https://continual.ai/post/the-modern-data-stack-ecosystem-spring-2022-edition)

This link no longer goes to the post. It returns a 404.

**Comment by ronikobrosly** [comment]
Thanks for the heads up @farmanp ! Just fixed it; now pointing to his Jordan Volz's Medium post.
